import { readFile, writeFile } from 'node:fs/promises';
const sources = ['202609200001_initial_schema.sql','202609210001_backend_operations.sql'];
const parts = await Promise.all(sources.map(async name => {
  const sql = await readFile(new URL(`../supabase/migrations/${name}`,import.meta.url),'utf8');
  return `-- SOURCE: ${name}\n` + sql.replace(/^begin;\s*$/m,'').replace(/^commit;\s*$/m,'');
}));
await writeFile(new URL('../supabase/schema.sql',import.meta.url),
  '-- REST: reconstructed schema for a NEW EMPTY Supabase project.\n' +
  '-- Run this entire file ONCE in SQL Editor. Includes both migrations.\n' +
  '-- Does not restore old data, Auth accounts or Backblaze credentials.\n' +
  '-- Generated by node scripts/build-schema.mjs; edit migration sources instead.\n\nbegin;\n\n'+parts.join('\n\n')+'\ncommit;\n');
