-- Minimal inferred schema, NOT a replacement for the customer's actual schema.
create role anon;
create role authenticated;
create schema auth;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to authenticated;
create table invoices(id uuid primary key default gen_random_uuid(),user_id uuid not null,seq_number bigint generated by default as identity,
 client text,client_nuit text,client_phone text,client_email text,description text,amount numeric,status text default 'Pending',
 issue_date date,due_date date,logo_bg text,company_profile_id text default 'primary',notes text);
create table quotes(id uuid primary key default gen_random_uuid(),user_id uuid not null,seq_number bigint generated by default as identity,
 client text,client_nuit text,client_phone text,client_email text,description text,amount numeric,status text default 'Pending',
 issue_date date,validity_days integer,logo_bg text,company_profile_id text default 'primary',notes text);
create table invoice_items(id uuid primary key default gen_random_uuid(),invoice_id uuid references invoices(id),description text check(description <> 'FAIL-LINE'),quantity numeric,unit_price numeric,sort_order integer);
create table quote_items(id uuid primary key default gen_random_uuid(),quote_id uuid references quotes(id),description text check(description <> 'FAIL-LINE'),quantity numeric,unit_price numeric,sort_order integer);
create table receipts(id uuid primary key default gen_random_uuid(),user_id uuid not null,seq_number bigint generated by default as identity,
 invoice_id uuid references invoices(id),invoice_ref text,client text,amount numeric,method text,method_pt text,payment_date date,company_profile_id text,notes text);
create table stock_items(id uuid primary key default gen_random_uuid(),user_id uuid not null,name text,stock_level numeric,created_at timestamptz default now());
create table general_sales(id uuid primary key default gen_random_uuid(),user_id uuid not null,seq_number bigint generated by default as identity,
 product_id uuid references stock_items(id),product_name text,sku text,quantity numeric,unit_price numeric,total_amount numeric,sale_date date,payment_method text,notes text);
create table debt_clients(id uuid primary key default gen_random_uuid(),user_id uuid not null,full_name text,movitel_number text,vodacom_number text,email text,address text,status text,created_at timestamptz default now());
create table contacts(id uuid primary key default gen_random_uuid(),user_id uuid not null,created_at timestamptz default now());
create table expenses(id uuid primary key default gen_random_uuid(),user_id uuid not null,seq_number bigint generated by default as identity);
do $$declare t text; begin
 for t in select unnest(array['invoices','quotes','receipts','stock_items','general_sales','debt_clients','contacts','expenses']) loop
 execute format('alter table %I enable row level security',t);
 execute format('create policy owner on %I to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid())',t);
 end loop;
end$$;
alter table invoice_items enable row level security;
create policy owner on invoice_items to authenticated using(exists(select 1 from invoices where id=invoice_id and user_id=auth.uid())) with check(exists(select 1 from invoices where id=invoice_id and user_id=auth.uid()));
alter table quote_items enable row level security;
create policy owner on quote_items to authenticated using(exists(select 1 from quotes where id=quote_id and user_id=auth.uid())) with check(exists(select 1 from quotes where id=quote_id and user_id=auth.uid()));
grant select,insert,update,delete on all tables in schema public to authenticated;
grant usage,select on all sequences in schema public to authenticated;
